# Generated by Django 4.1.4 on 2022-12-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gamename", models.CharField(max_length=100)),
                ("platform", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=250)),
            ],
        ),
    ]
