# Generated by Django 4.1.4 on 2022-12-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_score_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'get_latest_by': 'order_int'},
        ),
    ]
