# Generated by Django 4.1.4 on 2022-12-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_score_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={},
        ),
    ]
