# Generated by Django 4.1.4 on 2022-12-27 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_game_user"),
        ("main_app", "0007_alter_score_options"),
    ]

    operations = []
