# Generated by Django 4.1.4 on 2022-12-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_0002_game_user_0007_alter_score_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='gamer', max_length=100)),
                ('bio', models.CharField(max_length=500)),
            ],
        ),
    ]
