# Generated by Django 4.1.4 on 2023-01-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_profile"),
        ("main_app", "0010_memorygamescore_user"),
    ]

    operations = []
