# Generated by Django 4.1.4 on 2023-01-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0010_auto_20230103_1931"),
        ("main_app", "0012_alter_profile_username_delete_memorygamescore"),
    ]

    operations = []
