# Generated by Django 4.1.4 on 2023-01-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_profile_username'),
        ('main_app', '0013_merge_20230103_2024'),
    ]

    operations = [
    ]
