# Generated by Django 2.2.12 on 2023-01-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_merge_20230103_2355'),
        ('main_app', '0014_alter_game_id_alter_profile_id_alter_score_id'),
    ]

    operations = [
    ]
