# Generated by Django 4.1.4 on 2023-01-03 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0010_alter_profile_username"),
        ("main_app", "0014_alter_game_id_alter_profile_id_alter_score_id"),
    ]

    operations = []
