# Generated by Django 4.1.4 on 2023-01-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0014_merge_20230103_2355"),
        ("main_app", "0015_merge_20230103_2357"),
    ]

    operations = []
