# Generated by Django 4.1.4 on 2023-01-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0016_merge_20230104_2205"),
    ]

    operations = [
        migrations.CreateModel(
            name="Djangames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concentration", models.CharField(max_length=20)),
                ("simon", models.CharField(max_length=20)),
                ("minesweeper", models.CharField(max_length=20)),
            ],
        ),
    ]
