# Generated by Django 4.1.4 on 2023-01-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_djangames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Djangames',
        ),
    ]
