<<<<<<< HEAD
# Generated by Django 4.1.4 on 2023-01-05 19:03
=======
# Generated by Django 4.1.4 on 2023-01-05 18:59
>>>>>>> main

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("main_app", "0017_djangames"),
=======
        ('main_app', '0017_djangames'),
>>>>>>> main
    ]

    operations = [
        migrations.DeleteModel(
<<<<<<< HEAD
            name="Djangames",
=======
            name='Djangames',
>>>>>>> main
        ),
    ]
